[project]
name = "giga_agent_mcp_example"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastmcp>=2.13.0.2",
    "pytelegrambotapi>=4.29.1",
    "python-dotenv>=1.2.1",
]
